# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qt60PxWIYI7WQVPpMwhEihVxKlP-XRzj
"""

import json

def apply_corrections(extracted_json_path, corrections):
    """
    extracted_json_path: ONE JSON file:
      {"errors":[
         {"source_document":..., "page_number":..., "line_number":..., "word_number":...,
          "context":{"line_text":...}, "error":...},
         ...
      ]}

    corrections: list of dicts:
      {"source_document":..., "page_number":..., "line_number":..., "word_number":..., "corrected":...}

    Operation:
      - locate record by (source_document, page_number, line_number, word_number)
      - replace record["error"] inside record["context"]["line_text"] with correction["corrected"] (once)
      - overwrite the original JSON file
    """
    with open(extracted_json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    errors = data["errors"]

    # index by location
    idx = {}
    for i, r in enumerate(errors):
        key = (r["source_document"], r["page_number"], r["line_number"], r["word_number"])
        idx[key] = i

    # apply corrections
    for c in corrections:
        key = (c["source_document"], c["page_number"], c["line_number"], c["word_number"])
        i = idx[key]
        r = errors[i]

        line = r["context"]["line_text"]
        err = r["error"]
        corr_text = c["corrected"]

        r["context"]["line_text"] = line.replace(err, corr_text, 1)  # replace
        errors[i] = r

    # overwrite original file
    with open(extracted_json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)