"""config.py — Solanus voice-mimicker configuration (separate track; see PLAN.md + ETHICS.md).

Best-version-first choices from the 2026 deep research. Edit here; scripts consume it.
"""
from __future__ import annotations
from pathlib import Path

VOICE = Path(__file__).resolve().parent
PIPELINE_V3 = VOICE.parent
REPO = PIPELINE_V3.parent

DATA = VOICE / "data"
RAW = DATA / "raw"                 # the obtained 1945 transfer(s) / Echoes rips — work on COPIES
RESTORED = DATA / "restored"       # conservative restoration master (canonical clone reference source)
SUPERRES = DATA / "superres"       # OPTIONAL, NON-CANONICAL bandwidth-extended output (invented highs)
REFERENCES = DATA / "references"   # curated 5-15s reference clips
RENDERS = DATA / "renders"         # synthesized speech
for d in (DATA, RAW, RESTORED, SUPERRES, REFERENCES, RENDERS):
    d.mkdir(parents=True, exist_ok=True)

# --- restoration order (deepest damage first; two LIGHT denoise passes) ---
RESTORE_ORDER = ["declip", "declick", "decrackle", "dehum", "denoise_pass1", "denoise_pass2"]
DENOISE_MAX_DB = 18                 # above this -> hollow/phasey artifacts; prefer 2 light passes

# --- cloning models (best-version-first) ---
CLONE_PRIMARY = "cosyvoice3"        # Apache-2.0, ~3s ref, breath/soft-tone control
CLONE_COMPARATORS = ["llasa-8b", "f5-tts"]
STYLE_REF_MODEL = "openaudio-s1"    # (whisper)/(soft tone)/(breath) markers for the wispy voice
REFERENCE_CLIP_SECONDS = (5, 15)    # curate clips in this band
FROZEN_REFERENCE = REFERENCES / "solanus_ref_primary.wav"   # one frozen ref for cross-utterance consistency

# --- documented voice character (drives style prompts; from the historical record) ---
VOICE_NOTES = ("soft, high/thin, slightly wispy; weakened by childhood diphtheria; gentle, unhurried; "
               "Irish-American (Wisconsin); given to 'Deo gratias' / 'Thanks be to God'")

# --- text source: the trained text mimicker (NEVER free-form generation; see ETHICS.md) ---
TEXT_MIMICKER = PIPELINE_V3 / "mimicker"

# --- disclosure (default-on; embedded in every render) ---
DISCLOSURE = ("Synthetic voice of Blessed Solanus Casey — generated by AI; words drawn from his own writings. "
              "Produced with permission of the Capuchin Franciscan Province of St. Joseph.")
