"""Filesystem and runtime configuration for pipeline_v2.

The intent is to keep the new pipeline completely side-by-side with the
existing step_1/step_2/step_3/step_x layout while making dependencies explicit.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen = True)
class PipelinePaths:
    """Resolved directory layout for pipeline_v2 operations.

    Args:
        root_dir: Project root path.

    Returns:
        Dataclass instance containing all major source and destination paths.
    """

    root_dir: Path

    @property
    def pipeline_root(self) -> Path:
        """Return root directory for pipeline_v2 outputs and metadata.

        Args:
            None.

        Returns:
            Path to pipeline_v2 directory.
        """
        return self.root_dir / "pipeline_v2"

    @property
    def manifests_dir(self) -> Path:
        """Return directory containing structured few-shot manifests.

        Args:
            None.

        Returns:
            Path to pipeline_v2/manifests.
        """
        return self.pipeline_root / "manifests"

    @property
    def workspace_dir(self) -> Path:
        """Return working directory for generated intermediate artifacts.

        Args:
            None.

        Returns:
            Path to pipeline_v2/workspace.
        """
        return self.pipeline_root / "workspace"

    @property
    def sample_pages_dir(self) -> Path:
        """Return target directory for curated few-shot sample PDFs.

        Args:
            None.

        Returns:
            Path to pipeline_v2/workspace/sample_pages.
        """
        return self.workspace_dir / "sample_pages"

    @property
    def annotation_seed_dir(self) -> Path:
        """Return target directory for normalized annotation seed JSON files.

        Args:
            None.

        Returns:
            Path to pipeline_v2/workspace/annotation_seed.
        """
        return self.workspace_dir / "annotation_seed"

    @property
    def final_dir(self) -> Path:
        """Return editable annotation directory consumed by normalized editor.

        Args:
            None.

        Returns:
            Path to pipeline_v2/workspace/final.
        """
        return self.workspace_dir / "final"

    @property
    def cleaned_final_dir(self) -> Path:
        """Return export-ready final annotation directory.

        Args:
            None.

        Returns:
            Path to pipeline_v2/workspace/CLEANED_FINAL.
        """
        return self.workspace_dir / "CLEANED_FINAL"

    @property
    def source_polygon_pdfs(self) -> Path:
        """Return existing single-page PDF source generated by step_2.

        Args:
            None.

        Returns:
            Path to step_2/polygon_cropped_pdfs.
        """
        return self.root_dir / "step_2" / "polygon_cropped_pdfs"

    @property
    def source_normalized(self) -> Path:
        """Return existing normalized JSON source generated by legacy scripts.

        Args:
            None.

        Returns:
            Path to step_3/normalized.
        """
        return self.root_dir / "step_3" / "normalized"

    @property
    def source_final(self) -> Path:
        """Return existing final JSON edits from legacy workflow.

        Args:
            None.

        Returns:
            Path to step_3/final.
        """
        return self.root_dir / "step_3" / "final"

    @property
    def source_label_data(self) -> Path:
        """Return existing all-page labels from step_x workflow.

        Args:
            None.

        Returns:
            Path to step_x/label_page_data.
        """
        return self.root_dir / "step_x" / "label_page_data"


DEFAULT_RENDER_DPI = 150
DEFAULT_MANIFEST_NAME = "few_shot_manifest.json"


def get_project_root() -> Path:
    """Resolve project root from this module path.

    Args:
        None.

    Returns:
        Absolute path to repository root.
    """
    return Path(__file__).resolve().parent.parent


def get_paths() -> PipelinePaths:
    """Return resolved path contract for the current repository.

    Args:
        None.

    Returns:
        Immutable PipelinePaths instance.
    """
    return PipelinePaths(root_dir = get_project_root())


def ensure_pipeline_directories(paths: PipelinePaths) -> None:
    """Create pipeline_v2-owned directories used by stage scripts.

    This helper intentionally creates only new pipeline_v2 locations and does
    not modify any legacy step directories.

    Args:
        paths: Shared pipeline path contract.

    Returns:
        None. Missing directories are created.
    """
    required_directories = [
        paths.pipeline_root,
        paths.manifests_dir,
        paths.workspace_dir,
        paths.sample_pages_dir,
        paths.annotation_seed_dir,
        paths.final_dir,
        paths.cleaned_final_dir,
    ]

    for required_directory in required_directories:
        required_directory.mkdir(parents = True, exist_ok = True)
